# Generated by Django 4.2.5 on 2023-09-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'managed': False},
        ),
    ]
